"""
Property-based tests for collision-free paths generated by A* planner.

Feature: adaptnav-context-aware-warehouse-navigation
Property 7: Collision-Free Paths
Validates: Requirements 3.1
"""

import pytest
import numpy as np
from hypothesis import given, strategies as st, assume, settings
from adaptnav.core import WarehouseMap
from adaptnav.planning import AStarPlanner


# Custom strategies for generating test data
@st.composite
def warehouse_dimensions(draw):
    """Generate valid warehouse dimensions."""
    width = draw(st.floats(min_value=10.0, max_value=50.0))
    height = draw(st.floats(min_value=10.0, max_value=50.0))
    # Use reasonable resolution for path planning
    resolution = draw(st.floats(min_value=0.1, max_value=0.3))
    return width, height, resolution


@st.composite
def valid_position_pair(draw, warehouse_map, robot_radius):
    """Generate a pair of valid start and goal positions."""
    width = warehouse_map.width
    height = warehouse_map.height
    
    # Generate positions with sufficient margin from boundaries
    margin = robot_radius + 0.5
    
    start_x = draw(st.floats(min_value=margin, max_value=width - margin))
    start_y = draw(st.floats(min_value=margin, max_value=height - margin))
    
    goal_x = draw(st.floats(min_value=margin, max_value=width - margin))
    goal_y = draw(st.floats(min_value=margin, max_value=height - margin))
    
    # Ensure positions are collision-free
    assume(warehouse_map.is_collision_free(start_x, start_y, robot_radius))
    assume(warehouse_map.is_collision_free(goal_x, goal_y, robot_radius))
    
    # Ensure start and goal are sufficiently different
    distance = np.sqrt((goal_x - start_x)**2 + (goal_y - start_y)**2)
    assume(distance > 1.0)  # At least 1 meter apart
    
    return (start_x, start_y), (goal_x, goal_y)


@st.composite
def obstacle_configuration(draw, width, height, max_obstacles=5):
    """Generate a configuration of obstacles that doesn't block all paths."""
    num_obstacles = draw(st.integers(min_value=0, max_value=max_obstacles))
    obstacles = []
    
    for _ in range(num_obstacles):
        # Place obstacles away from edges to ensure some free space
        margin = 2.0
        obs_x = draw(st.floats(min_value=margin, max_value=width - margin))
        obs_y = draw(st.floats(min_value=margin, max_value=height - margin))
        
        # Keep obstacles reasonably sized
        obs_width = draw(st.floats(min_value=0.5, max_value=min(3.0, width * 0.2)))
        obs_height = draw(st.floats(min_value=0.5, max_value=min(3.0, height * 0.2)))
        
        obstacles.append((obs_x, obs_y, obs_width, obs_height))
    
    return obstacles


@st.composite
def robot_radius_strategy(draw):
    """Generate a valid robot radius."""
    return draw(st.floats(min_value=0.2, max_value=0.5))


@pytest.mark.property
class TestCollisionFreePathsProperties:
    """Property-based tests for collision-free paths from A* planner."""
    
    @given(
        dims=warehouse_dimensions(),
        robot_radius=robot_radius_strategy(),
        obstacles=st.data()
    )
    @settings(max_examples=100, deadline=60000)
    def test_all_path_waypoints_are_collision_free(self, dims, robot_radius, obstacles):
        """
        Property: For any valid start and goal positions in the warehouse, 
        if the A* planner returns a path, then every waypoint on that path 
        should be collision-free with respect to static obstacles 
        (minimum 0.3m clearance).
        
        **Validates: Requirements 3.1**
        """
        width, height, resolution = dims
        warehouse_map = WarehouseMap(width=width, height=height, resolution=resolution)
        
        # Add some obstacles but ensure they don't completely block the warehouse
        obstacle_config = obstacles.draw(obstacle_configuration(width, height, max_obstacles=3))
        for obs_x, obs_y, obs_width, obs_height in obstacle_config:
            warehouse_map.set_obstacle(obs_x, obs_y, obs_width, obs_height)
        
        # Generate valid start and goal positions
        try:
            positions = obstacles.draw(valid_position_pair(warehouse_map, robot_radius))
            (start_x, start_y), (goal_x, goal_y) = positions
        except:
            # Skip if we can't generate valid positions (too many obstacles)
            assume(False)
        
        # Create A* planner
        planner = AStarPlanner(warehouse_map, robot_radius=robot_radius, timeout_seconds=5.0)
        
        # Plan path
        path = planner.plan_path(start_x, start_y, goal_x, goal_y)
        
        # If planner returns a path, all waypoints must be collision-free
        if path is not None:
            assert len(path.waypoints) >= 2, "Path should have at least start and goal waypoints"
            
            # Check each waypoint for collision-free status
            for i, waypoint in enumerate(path.waypoints):
                is_free = warehouse_map.is_collision_free(
                    waypoint.x, waypoint.y, radius=robot_radius
                )
                assert is_free, (
                    f"Waypoint {i} at ({waypoint.x:.3f}, {waypoint.y:.3f}) "
                    f"is not collision-free with robot radius {robot_radius:.3f}m. "
                    f"Path has {len(path.waypoints)} waypoints."
                )
    
    @given(
        dims=warehouse_dimensions(),
        robot_radius=robot_radius_strategy(),
        obstacles=st.data()
    )
    @settings(max_examples=100, deadline=60000)
    def test_path_maintains_minimum_clearance(self, dims, robot_radius, obstacles):
        """
        Property: For any path returned by the A* planner, every waypoint
        should maintain at least the specified robot radius clearance from
        all obstacles.
        
        **Validates: Requirements 3.1**
        """
        width, height, resolution = dims
        warehouse_map = WarehouseMap(width=width, height=height, resolution=resolution)
        
        # Add obstacles
        obstacle_config = obstacles.draw(obstacle_configuration(width, height, max_obstacles=2))
        for obs_x, obs_y, obs_width, obs_height in obstacle_config:
            warehouse_map.set_obstacle(obs_x, obs_y, obs_width, obs_height)
        
        # Generate valid positions
        try:
            positions = obstacles.draw(valid_position_pair(warehouse_map, robot_radius))
            (start_x, start_y), (goal_x, goal_y) = positions
        except:
            assume(False)
        
        # Create planner with specific clearance requirement
        clearance_radius = max(robot_radius, 0.3)  # Minimum 0.3m as per requirements
        planner = AStarPlanner(warehouse_map, robot_radius=clearance_radius, timeout_seconds=5.0)
        
        # Plan path
        path = planner.plan_path(start_x, start_y, goal_x, goal_y)
        
        if path is not None:
            # Verify minimum clearance for each waypoint
            for i, waypoint in enumerate(path.waypoints):
                # Check with the required clearance radius
                is_clear = warehouse_map.is_collision_free(
                    waypoint.x, waypoint.y, radius=clearance_radius
                )
                assert is_clear, (
                    f"Waypoint {i} at ({waypoint.x:.3f}, {waypoint.y:.3f}) "
                    f"does not maintain minimum clearance of {clearance_radius:.3f}m"
                )
    
    @given(
        dims=warehouse_dimensions(),
        robot_radius=robot_radius_strategy()
    )
    @settings(max_examples=100, deadline=60000)
    def test_empty_warehouse_paths_are_collision_free(self, dims, robot_radius):
        """
        Property: In an empty warehouse, any path returned by A* planner
        should have all waypoints collision-free.
        
        **Validates: Requirements 3.1**
        """
        width, height, resolution = dims
        warehouse_map = WarehouseMap(width=width, height=height, resolution=resolution)
        
        # Generate random start and goal positions with margin
        margin = robot_radius + 0.5
        start_x = np.random.uniform(margin, width - margin)
        start_y = np.random.uniform(margin, height - margin)
        goal_x = np.random.uniform(margin, width - margin)
        goal_y = np.random.uniform(margin, height - margin)
        
        # Ensure positions are different
        distance = np.sqrt((goal_x - start_x)**2 + (goal_y - start_y)**2)
        assume(distance > 1.0)
        
        # Create planner
        planner = AStarPlanner(warehouse_map, robot_radius=robot_radius, timeout_seconds=5.0)
        
        # Plan path
        path = planner.plan_path(start_x, start_y, goal_x, goal_y)
        
        # Path should exist in empty warehouse
        assert path is not None, "A* should find path in empty warehouse"
        
        # All waypoints should be collision-free
        for i, waypoint in enumerate(path.waypoints):
            is_free = warehouse_map.is_collision_free(
                waypoint.x, waypoint.y, radius=robot_radius
            )
            assert is_free, (
                f"Waypoint {i} at ({waypoint.x:.3f}, {waypoint.y:.3f}) "
                f"should be collision-free in empty warehouse"
            )
    
    @given(
        dims=warehouse_dimensions(),
        robot_radius=robot_radius_strategy(),
        obstacles=st.data()
    )
    @settings(max_examples=100, deadline=60000)
    def test_path_waypoints_within_warehouse_bounds(self, dims, robot_radius, obstacles):
        """
        Property: All waypoints in any path returned by A* planner should be
        within the warehouse boundaries, accounting for robot radius.
        
        **Validates: Requirements 3.1**
        """
        width, height, resolution = dims
        warehouse_map = WarehouseMap(width=width, height=height, resolution=resolution)
        
        # Add some obstacles
        obstacle_config = obstacles.draw(obstacle_configuration(width, height, max_obstacles=2))
        for obs_x, obs_y, obs_width, obs_height in obstacle_config:
            warehouse_map.set_obstacle(obs_x, obs_y, obs_width, obs_height)
        
        # Generate valid positions
        try:
            positions = obstacles.draw(valid_position_pair(warehouse_map, robot_radius))
            (start_x, start_y), (goal_x, goal_y) = positions
        except:
            assume(False)
        
        # Create planner
        planner = AStarPlanner(warehouse_map, robot_radius=robot_radius, timeout_seconds=5.0)
        
        # Plan path
        path = planner.plan_path(start_x, start_y, goal_x, goal_y)
        
        if path is not None:
            # Check bounds for each waypoint
            for i, waypoint in enumerate(path.waypoints):
                # Waypoint center should be within bounds
                assert 0 <= waypoint.x <= width, (
                    f"Waypoint {i} x-coordinate {waypoint.x:.3f} is outside bounds [0, {width}]"
                )
                assert 0 <= waypoint.y <= height, (
                    f"Waypoint {i} y-coordinate {waypoint.y:.3f} is outside bounds [0, {height}]"
                )
                
                # Robot footprint should not extend outside bounds
                assert waypoint.x >= robot_radius, (
                    f"Waypoint {i} at ({waypoint.x:.3f}, {waypoint.y:.3f}) "
                    f"would place robot outside left boundary (radius: {robot_radius:.3f})"
                )
                assert waypoint.x <= width - robot_radius, (
                    f"Waypoint {i} at ({waypoint.x:.3f}, {waypoint.y:.3f}) "
                    f"would place robot outside right boundary (radius: {robot_radius:.3f})"
                )
                assert waypoint.y >= robot_radius, (
                    f"Waypoint {i} at ({waypoint.x:.3f}, {waypoint.y:.3f}) "
                    f"would place robot outside bottom boundary (radius: {robot_radius:.3f})"
                )
                assert waypoint.y <= height - robot_radius, (
                    f"Waypoint {i} at ({waypoint.x:.3f}, {waypoint.y:.3f}) "
                    f"would place robot outside top boundary (radius: {robot_radius:.3f})"
                )
    
    @given(
        dims=warehouse_dimensions(),
        robot_radius=robot_radius_strategy(),
        obstacles=st.data()
    )
    @settings(max_examples=100, deadline=60000)
    def test_path_connectivity_is_valid(self, dims, robot_radius, obstacles):
        """
        Property: For any path returned by A* planner, consecutive waypoints
        should be reachable from each other (no large gaps that would require
        the robot to teleport).
        
        **Validates: Requirements 3.1**
        """
        width, height, resolution = dims
        warehouse_map = WarehouseMap(width=width, height=height, resolution=resolution)
        
        # Add obstacles
        obstacle_config = obstacles.draw(obstacle_configuration(width, height, max_obstacles=2))
        for obs_x, obs_y, obs_width, obs_height in obstacle_config:
            warehouse_map.set_obstacle(obs_x, obs_y, obs_width, obs_height)
        
        # Generate valid positions
        try:
            positions = obstacles.draw(valid_position_pair(warehouse_map, robot_radius))
            (start_x, start_y), (goal_x, goal_y) = positions
        except:
            assume(False)
        
        # Create planner
        planner = AStarPlanner(warehouse_map, robot_radius=robot_radius, timeout_seconds=5.0)
        
        # Plan path
        path = planner.plan_path(start_x, start_y, goal_x, goal_y)
        
        if path is not None and len(path.waypoints) > 1:
            # Check connectivity between consecutive waypoints
            max_step_size = resolution * np.sqrt(2) * 2  # Allow for diagonal moves plus some margin
            
            for i in range(len(path.waypoints) - 1):
                current = path.waypoints[i]
                next_wp = path.waypoints[i + 1]
                
                distance = np.sqrt(
                    (next_wp.x - current.x)**2 + (next_wp.y - current.y)**2
                )
                
                assert distance <= max_step_size, (
                    f"Gap between waypoints {i} and {i+1} is too large: {distance:.3f}m "
                    f"(max allowed: {max_step_size:.3f}m). "
                    f"Waypoint {i}: ({current.x:.3f}, {current.y:.3f}), "
                    f"Waypoint {i+1}: ({next_wp.x:.3f}, {next_wp.y:.3f})"
                )
    
    @given(
        dims=warehouse_dimensions(),
        robot_radius=robot_radius_strategy(),
        obstacles=st.data()
    )
    @settings(max_examples=100, deadline=60000)
    def test_path_starts_and_ends_correctly(self, dims, robot_radius, obstacles):
        """
        Property: For any path returned by A* planner, the first waypoint
        should be close to the start position and the last waypoint should
        be close to the goal position.
        
        **Validates: Requirements 3.1**
        """
        width, height, resolution = dims
        warehouse_map = WarehouseMap(width=width, height=height, resolution=resolution)
        
        # Add obstacles
        obstacle_config = obstacles.draw(obstacle_configuration(width, height, max_obstacles=2))
        for obs_x, obs_y, obs_width, obs_height in obstacle_config:
            warehouse_map.set_obstacle(obs_x, obs_y, obs_width, obs_height)
        
        # Generate valid positions
        try:
            positions = obstacles.draw(valid_position_pair(warehouse_map, robot_radius))
            (start_x, start_y), (goal_x, goal_y) = positions
        except:
            assume(False)
        
        # Create planner
        planner = AStarPlanner(warehouse_map, robot_radius=robot_radius, timeout_seconds=5.0)
        
        # Plan path
        path = planner.plan_path(start_x, start_y, goal_x, goal_y)
        
        if path is not None:
            assert len(path.waypoints) >= 2, "Path should have at least 2 waypoints"
            
            # Check start waypoint
            start_waypoint = path.waypoints[0]
            start_distance = np.sqrt(
                (start_waypoint.x - start_x)**2 + (start_waypoint.y - start_y)**2
            )
            # Allow for grid discretization error
            max_start_error = resolution * np.sqrt(2)
            assert start_distance <= max_start_error, (
                f"Start waypoint ({start_waypoint.x:.3f}, {start_waypoint.y:.3f}) "
                f"is too far from requested start ({start_x:.3f}, {start_y:.3f}): "
                f"distance {start_distance:.3f}m > {max_start_error:.3f}m"
            )
            
            # Check goal waypoint
            goal_waypoint = path.waypoints[-1]
            goal_distance = np.sqrt(
                (goal_waypoint.x - goal_x)**2 + (goal_waypoint.y - goal_y)**2
            )
            max_goal_error = resolution * np.sqrt(2)
            assert goal_distance <= max_goal_error, (
                f"Goal waypoint ({goal_waypoint.x:.3f}, {goal_waypoint.y:.3f}) "
                f"is too far from requested goal ({goal_x:.3f}, {goal_y:.3f}): "
                f"distance {goal_distance:.3f}m > {max_goal_error:.3f}m"
            )